datacommonsorg/import

tool/pom.xml, tool/src/main/java/org/datacommons/tool/GenMcf.java, tool/src/main/java/org/datacommons/tool/Lint.java, tool/src/main/java/org/datacommons/tool/Main.java, tool/src/main/java/org/datacommons/tool/Processor.java, util/pom.xml, util/src/main/java/org/datacommons/proto/Debug.java, util/src/main/java/org/datacommons/util/LogWrapper.java, util/src/main/java/org/datacommons/util/McfParser.java, util/src/main/java/org/datacommons/util/TmcfCsvParser.java, util/src/main/proto/Debug.proto, util/src/test/java/org/datacommons/util/LogWrapperTest.java, util/src/test/java/org/datacommons/util/McfParserTest.java, util/src/test/java/org/datacommons/util/McfUtilTest.java, util/src/test/java/org/datacommons/util/TmcfCsvParserTest.java, util/src/test/resources/org/datacommons/util/LogWrapperTest_result.json
* Add a LogWrapper class to provide helpers for logging to the Debug.Log proto on a file
* Plumb the LogWrapper into MCFParser and TmcfCsvParser classes, replacing every `assert` with a logging call
* Finally, produce a JSON report that can then be viewed in a tabular way using something like jsongrid.com. In future, we can see about producing a self-contained html, maybe.
Example run on a real files:
```
$ dc-import lint Google_Health_COVID19_US*
19:57:06.397 [main] INFO  org.datacommons.tool.Lint - Input includes 1 MCF file(s), 1 TMCF file(s), 1 CSV file(s)
19:57:06.504 [main] INFO  org.datacommons.tool.Processor - Checked Google_Health_COVID19_US_StatisticalVariables.mcf with 12 nodes
19:57:30.730 [main] INFO  org.datacommons.tool.Processor - Processed 100000 rows of …
```
=> Implement a simple log wrapper, plumb it into the parsers, and produce a JSON report

tool/src/main/java/org/datacommons/tool/Processor.java, util/src/main/java/org/datacommons/proto/Debug.java, util/src/main/java/org/datacommons/proto/Mcf.java, util/src/main/java/org/datacommons/util/LogWrapper.java, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/main/java/org/datacommons/util/McfMutator.java, util/src/main/java/org/datacommons/util/McfParser.java, util/src/main/java/org/datacommons/util/McfUtil.java, util/src/main/java/org/datacommons/util/TestUtil.java, util/src/main/java/org/datacommons/util/TmcfCsvParser.java, util/src/main/proto/Debug.proto, util/src/main/proto/Mcf.proto, util/src/test/java/org/datacommons/util/McfCheckerTest.java, util/src/test/java/org/datacommons/util/McfMutatorTest.java, util/src/test/java/org/datacommons/util/McfParserTest.java, util/src/test/java/org/datacommons/util/McfUtilTest.java, util/src/test/java/org/datacommons/util/TmcfCsvParserTest.java, util/src/test/resources/org/datacommons/util/LogWrapperTest_result.json, util/src/test/resources/org/datacommons/util/TmcfCsvParser_SVO.csv, util/src/test/resources/org/datacommons/util/TmcfCsvParser_SVO_Failure.tmcf
This PR largely implements logic in g3's [mcf_schema_util.cc](https://source.corp.google.com/piper///depot/google3/datacommons/import/util/mcf_schema_util.cc).
With this PR, modulo some minor transformation TODOs, the tool should have parity with cpp code for parsing MCF/TMCF/CSV and checking them.
So, for imports where the place DCIDs are mapped (because no resolution support yet), if the tool reports no errors/warnings, then the import should be structurally sane (or its a tool bug).
=> Implement MCF checking and transformations

util/src/main/java/org/datacommons/util/LogWrapper.java, util/src/main/java/org/datacommons/util/McfParser.java, util/src/test/resources/org/datacommons/util/McfParserTest_ResolvedGraph.mcf, util/src/test/resources/org/datacommons/util/McfParserTest_ResolvedGraph.textproto
A user error resulted in duplicate typeOf values. And this then causes duplicate error messages, like below, because we were not deduplicating within a single node.
=> Bug fix: deduplicate single node content

util/src/main/java/org/datacommons/util/ComplexValueParser.java, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/main/java/org/datacommons/util/McfParser.java, util/src/main/java/org/datacommons/util/McfUtil.java, util/src/main/java/org/datacommons/util/TmcfCsvParser.java, util/src/test/java/org/datacommons/util/ComplexValueParserTest.java, util/src/test/java/org/datacommons/util/McfUtilTest.java
- instead of using a BiConsumer, create a new class to act as an ErrCb that can take in more arguments
- ErrCb can be used to set details such as Node, Property, Column, Value, Counter Suffix, Counter Prefix, etc. and those can be then used in the message used for logging an error/warning
=> Updates to ErrCb

tool/pom.xml, tool/src/main/java/org/datacommons/tool/Processor.java, tool/src/test/java/org/datacommons/tool/GenMcfTest.java, tool/src/test/java/org/datacommons/tool/LintTest.java, tool/src/test/java/org/datacommons/tool/TestUtil.java, tool/src/test/resources/org/datacommons/tool/Csv1.csv, tool/src/test/resources/org/datacommons/tool/GenMcfTest_FatalTmcfReport.json, tool/src/test/resources/org/datacommons/tool/GenMcfTest_SuccessTmcfGenerated.mcf, tool/src/test/resources/org/datacommons/tool/GenMcfTest_SuccessTmcfReport.json, tool/src/test/resources/org/datacommons/tool/LintTest.mcf, tool/src/test/resources/org/datacommons/tool/LintTest_AllThreeFilesReport.json, tool/src/test/resources/org/datacommons/tool/LintTest_McfAndTmcfReport.json, tool/src/test/resources/org/datacommons/tool/Tmcf1.tmcf, tool/src/test/resources/org/datacommons/tool/TmcfWithErrors.tmcf, util/src/main/java/org/datacommons/util/LogWrapper.java, util/src/main/java/org/datacommons/util/McfMutator.java, util/src/main/java/org/datacommons/util/McfParser.java, util/src/main/java/org/datacommons/util/TmcfCsvParser.java
- Added end to end tests that invoke GenMcf and Lint
- Fixed a few small bugs along the way
-  output log when there is a fatal tmcf failure during genmcf
-  handle ConcurrentModificationException thrown by McfMutator.mutate
-  log Mutator_MissingTypeOf counter when typeOf is missing
-  handle some NullPointerExceptions
-  Small message fixes
=> Add End to End tests

tool/src/main/java/org/datacommons/tool/GenMcf.java, tool/src/main/java/org/datacommons/tool/Lint.java, tool/src/main/java/org/datacommons/tool/Processor.java, tool/src/test/java/org/datacommons/tool/LintTest.java, util/pom.xml, util/src/main/java/org/datacommons/util/ExistenceChecker.java, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/main/java/org/datacommons/util/TmcfCsvParser.java, util/src/test/java/org/datacommons/util/ExistenceCheckerTest.java, util/src/test/java/org/datacommons/util/McfCheckerTest.java, util/src/test/java/org/datacommons/util/TmcfCsvParserTest.java
This checks that references to schema-like things exist in the KG or the local graph (i.e., other provided MCFs).
Notably, for performance reasons, for now it does not validate references to place entities (`observationAbout` value).
Existence check results are cached locally to avoid future calls.  Batching would be nice, but that would be a more significant refactor to the call-sites (e.g., we need to save the per-reference context required for logging), so we can consider in future.
Testing: there's a unit test for ExistenceChecker and another to confirm that individual nodes are existence-checked in McfChecker. Plan to add an e2e once the LintTest is generalized.
TODO: get some real testing and enable `-e` by default...
=> Implement existence checks by calling DC API (needs to be enabled by -e)

tool/src/main/java/org/datacommons/tool/Lint.java, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/report.json
Ran this against all schema MCF, feels reasonably usable, though I'm sure there are uncovered bugs. At this point it might be more useful than without it.
=> Enable existence checks by default

server/src/main/java/org/datacommons/server/ServerCommand.java, tool/src/main/java/org/datacommons/tool/GenMcf.java, tool/src/main/java/org/datacommons/tool/Lint.java, tool/src/main/java/org/datacommons/tool/Processor.java, tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/report.json, util/src/main/java/org/datacommons/util/ExistenceChecker.java, util/src/main/java/org/datacommons/util/FileGroup.java, util/src/main/java/org/datacommons/util/LogCb.java, util/src/main/java/org/datacommons/util/LogWrapper.java, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/main/java/org/datacommons/util/TmcfCsvParser.java, util/src/test/java/org/datacommons/util/ExistenceCheckerTest.java, util/src/test/java/org/datacommons/util/McfCheckerTest.java
Previously, we relied only on caching prior checks. But each DC call from India takes ~250ms, so ~5K calls (e.g., to validate [all SVs](https://github.com/datacommonsorg/schema/tree/main/stat_vars)), which takes 5m from my laptop (and 2m from cloud-top), takes 20m from India.
With this change, we first collect checks (along with a callback) to batch and invoke DC calls when we have collected enough. The same SV validation now takes ~8s and makes 53 calls (see screenshot).
Additional changes:
1. Add a check that all stat-vars include a DCID.  We could in theory have StatVars without DCID and we compute it, but in practice we don't.  This tripped @ajaits.
2. Fix minor regression introduced [here](https://github.com/datacommonsorg/import/pull/34/files#diff-368ed99815e72875840d6857e431260a508c …
=> Batch existence check requests to DC

util/src/main/java/org/datacommons/util/DcidGenerator.java, util/src/main/java/org/datacommons/util/Vocabulary.java, util/src/test/java/org/datacommons/util/DcidGeneratorTest.java
Port the [prod DCID generation library](http://google3/datacommons/util/dcid.h) to Java.
Notably missing is support for "small hashed IDs", used for place types, Source, Curator and Provenance, because [Java doesn't seem to have](https://guava.dev/releases/21.0/api/docs/com/google/common/hash/Hashing.html) farmhash32 that prod uses. If we deviate from prod IDs that's worse than not supporting it.
I don't think this should affect most imports, but we'll see...
=> DCID Generator Library

tool/src/main/java/org/datacommons/tool/GenMcf.java, tool/src/main/java/org/datacommons/tool/Lint.java, tool/src/main/java/org/datacommons/tool/Main.java, tool/src/main/java/org/datacommons/tool/Processor.java, tool/src/test/java/org/datacommons/tool/GenMcfTest.java, tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/report.json, tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/report.json, util/src/main/java/org/datacommons/util/DcidGenerator.java, util/src/main/java/org/datacommons/util/ExistenceChecker.java, util/src/main/java/org/datacommons/util/ExternalIdResolver.java, util/src/main/java/org/datacommons/util/LogWrapper.java, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/main/java/org/datacommons/util/TestUtil.java
1. Use POST requests and increase existence-check batching by 10x (largely for India latencies)
2. Add more log messages for resolution flow
3. Add a LOCAL resolution mode where we don't need two passes, or recon calls
4. Fix some double-counting bugs in McfChecker lib
=> Improve existence-check batching and resolution usability

util/src/main/java/org/datacommons/util/StatChecker.java
- remove synchronized from extractSeriesFromGraph which is a method called for every node
=> Optimize extractSeriesFromGraph method in StatChecker

tool/pom.xml, tool/src/test/java/org/datacommons/tool/GenMcfTest.java, tool/src/test/java/org/datacommons/tool/LintTest.java, tool/src/test/java/org/datacommons/tool/TestUtil.java
- When generating charts for the summary report, depending on the machine, the dimensions may vary slightly. In the e2e tests, instead of comparing the actual vs expected summary_report.html files just as strings, compare the elements on the page and their text content. This tests the important parts of the html file
=> Update html file comparison in e2e tests

tool/src/main/java/org/datacommons/tool/Main.java, tool/src/test/java/org/datacommons/tool/GenMcfTest.java, tool/src/test/java/org/datacommons/tool/LintTest.java, tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/resolution/input/covid.tmcf, tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/report.json, tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/table_mcf_nodes_covid.mcf, tool/src/test/resources/org/datacommons/tool/genmcf/statchecks/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/statchecks/output/summary_report.html, util/src/main/resources/SummaryReport.ftl
- Make summary report generation the default 
- Add max width to columns to handle extra long variable names: [summary report with long variable name](https://htmlpreview.github.io/?https://github.com/chejennifer/import/blob/43e72f05937745ff6ab52623e00489594459feeb/tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/summary_report.html)
=> Enable Summary Report Generation as default

util/src/main/java/org/datacommons/util/ExistenceChecker.java, util/src/main/java/org/datacommons/util/ExternalIdResolver.java
This fixes the presubmit failures [here](https://pantheon.corp.google.com/cloud-build/builds/3f58eb85-10f5-4d06-8334-a4d6954ccd4d;step=0?project=879489846695).
Possible reason:  There seems to have been a regression in Java 11 HttpClient, wherein, if the server supports only HTTP 1.1 (as our servers do), the default Java HttpClient connection (which uses HTTP2) throws this error.  See details in these bugs: [1](https://bugs.openjdk.java.net/browse/JDK-8218546), [2](https://bugs.openjdk.java.net/browse/JDK-8218623)
I suspect the Docker image that CloudBuild uses somehow uses a minor version of Java that includes the regression bug, but not the subsequent fix.  Handle this by setting the HTTP version that the servers support.
Bonus:  upgrade recon API endpoint to staging
=> Pass HTTP 1.1 version for DC calls

tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/summary_report.html, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/test/java/org/datacommons/util/McfCheckerTest.java
If a StatVar does not have a populationType, the tool will now generate a warning instead of an error. Note that if a StatVar has a 'PopulationType' field instead of 'populationType', the tool will still generate an error.
=> Removing the requirement for StatVars to have a populationType.

util/src/main/java/org/datacommons/util/McfChecker.java, util/src/test/java/org/datacommons/util/McfCheckerTest.java
This is so that we can have schema-less SVs that have mprops that refer to the SV itself (which may start with an upper case letter).
=> Support schemaless SVs with init-cap mprop

tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/report.json, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/summary_report.html, util/src/main/java/org/datacommons/util/ExistenceChecker.java, util/src/main/java/org/datacommons/util/McfChecker.java
- fix error when running LintTest which was caused by passing an empty dcid to the /node/property-values call. Do this by adding checks that dcid is not empty
- fix bug of infinite loop of independent RPC call issued -> RPC call fails -> same independent RPC call issued
=> Fix test errors

tool/src/main/java/org/datacommons/tool/Main.java
`usage.md` was recently added (#118) with revised documentation of the flags (and more), however, the CLI documentation coded into the tool at `Main.java` was outdated.
Updated these descriptions while keeping the verbose descriptions out for brevity.
Resolves [this comment](https://github.com/datacommonsorg/import/pull/118#discussion_r897358478) on #118, mentioning that we should update the CLI documentation to match the changes in that PR.
=> [docs] update CLI flag documentation to match `docs/usage.md`

wizard/src/types.ts, wizard/src/utils/obs_generation.test.tsx, wizard/src/utils/obs_generation.ts
The main API returns observations as a map, associated with rows, so that the frontend can decide to link it to display rows.
There's also a helper to produce a text string from the map that's to be tweaked as necessary.
=> Generate observations using mapping and csvData

tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/localidresolution/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/statchecks/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/lint/statchecks/output/summary_report.html, util/src/main/resources/SummaryReport.ftl
Closes #160 
---
add buttons under the "Series Summaries for Sample Places" header that
expand or collapse all `<details>` tags for sample places.
uses a javascript function that queries the page for `<details>` tags, and
sets the ".open" boolean attribute on all of them.
=> add "expand/collapse all" buttons to summary_report

tool/src/test/resources/org/datacommons/tool/genmcf/localidresolution/output/failed_table_mcf_nodes_covid.mcf, tool/src/test/resources/org/datacommons/tool/genmcf/localidresolution/output/report.json, tool/src/test/resources/org/datacommons/tool/genmcf/measurementresult/output/table_mcf_nodes_acre.mcf, tool/src/test/resources/org/datacommons/tool/genmcf/statchecks/output/table_mcf_nodes_covid.mcf, tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/output/report.json, tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/output/table_mcf_nodes_SuccessTmcf.mcf, tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json, util/src/main/java/org/datacommons/util/TmcfCsvParser.java
https://github.com/datacommonsorg/import/blob/d995b5c52d2750cb8ec4b5cce564209edda18e02/util/src/main/java/org/datacommons/util/TmcfCsvParser.java#L35-L36
Switch implementation to use a private variable because csvParser.getCurrentLineNumber() does not increment last line when the row does not end in a newline.
Unit tests pass. I reviewed the goldens by hand to make sure that the only changes were the IDs of the last rows in the inputs. Specifically, these should increment by one since they were previously one less than the correct value.
=> Fix TmcfCsvParser last line number is not incremented

tool/src/main/java/org/datacommons/tool/Processor.java, tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/report.json, tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/summary_report.html, tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/input/SuccessTmcf.csv, util/src/main/java/org/datacommons/util/TmcfCsvParser.java
This PR makes 3 fixes:
1. Strips out BOM characters apparently found at the beginning of old Excel sheets
2. Propagates exceptions during CSV processing so we fail loudly
3. Allow empty column names in CSVs
The first two issues were found from Techsoup CSVs.
=> Support BOM, propagate exceptions and allow empty column names

simple/stats/constants.py, simple/stats/importer.py, simple/stats/sample/countries/debug_resolve.csv, simple/stats/sample/countries/input.csv, simple/stats/sample/countries/observations.csv
* Entity values prefixed with `dcid:` are considered pre-resolved.
* Allows users to manually override dcids.
=> Support pre-resolved entities.

simple/stats/constants.py, simple/stats/importer.py, simple/stats/main.py, simple/util/dc_client.py, simple/util/ngram_matcher.py
* Outputs csvs in wide format by default (i.e. without "unpivotting").
* Allows overriding API root via env variable (e.g. to call autopush api).
* Supports debug flag (in code) to write entities to file for debugging.
=> Output csvs in wide format by default.

simple/requirements.txt, simple/stats/importer.py, simple/util/filehandler.py
* Created a generic `FileHandler` abstraction with local and GCS implementations.
* GCS paths must begin with `gs://`.
* Example of GCS usage:
+ `python3 main.py --input_path=gs://datcom-floret-dev-resources/data/observations-floretcountrydata.csv --output_dir=gs://datcom-floret-dev-resources/temp/`
+ The above command read the CSV from the GCS path and output the files to another GCS path [here](https://screenshot.googleplex.com/8DZktSQaTxV2QNw).
* A mix of local and GCS paths for inputs / outputs is also supported.
+ e.g. `python3 main.py --input_path=gs://datcom-floret-dev-resources/data/observations-floretcountrydata.csv --output_dir=data/`
* Note that input folders are not yet supported. That will be implemented soon.
=> Add support for GCS paths.

run_test.sh, simple/stats/db.py, simple/stats/runner.py, simple/tests/stats/db_test.py
* Verified against both sqlite and cloud sql.
```
mysql> use datacommons;
Database changed
mysql> show tables;
+-----------------------+
| Tables_in_datacommons |
+-----------------------+
| imports               |
| observations          |
| triples               |
+-----------------------+
3 rows in set (0.05 sec)
mysql> select * from imports;
+---------------------+---------+------------------------------+
| imported_at         | status  | metadata                     |
+---------------------+---------+------------------------------+
| 2023-12-12 10:32:16 | SUCCESS | {"numVars": 4, "numObs": 58} |
+---------------------+---------+------------------------------+
1 row in set (0.05 sec)
mysql> 
```
=> Write import info to a new imports table.

run_test.sh, simple/sample/README.md, simple/stats/constants.py, simple/stats/main.py, simple/stats/runner.py
* In practice, RSI is used only for importing directories and not individual files (including by the load data tool).
* This PR removes support for importing individual files to eliminate this tech debt.
* This changes the command line flag from `--input_path` to `--input_dir`. To account for this change in the admin tool, we'll update [this code](https://github.com/datacommonsorg/website/blob/fa272ab47c70de1e5af47c681b887046152b6e25/server/routes/admin/html.py#L64) in the website repo when updating its submodules.
=> Remove support for importing individual files.

simple/requirements.txt, simple/util/dc_client.py
* Partitions place entities into chunks of 500 entities each and resolves them concurrently.
* This will be needed for importing large datasets such as [this one](https://docs.google.com/spreadsheets/d/18gtY3mCtxz6HDcs6iCd4cFi9c6SpUdsIvKl1nrT5SrQ/edit#gid=1171898663) which has 250K+ lat-lngs.
* Verified by running against the sample dataset and changing batch sizes locally.
+ Will add integration tests and run them in the cloud so such functionality will be auto tested on each PR.
=> Resolve place entities concurrently.

build/ci/cloudbuild.push_simple.yaml, build/simple/run.sh
* Uses `--network=cloudbuild` flag when building the docker image. This enables the docker container to use default GCP creds. [[Reference]](https://cloud.google.com/build/docs/build-config-file-schema)
* With this change, we can create RSI jobs in Cloud Run that can use the project's service account to read / write from GCS.
* Will create a short guide for the team soon.
=> Use default GCP creds in docker container.

simple/stats/events_importer.py, simple/stats/observations_importer.py
* Replaced the pandas `replace` method with the `map` method.
+ Without this change, the code got stuck when writing a dataset with 250K entities.
* Also, we are now renaming columns early so we can refer to them by name vs by index.
=> Improve performance of writing resolved entities.

simple/kg_util/mcf_parser.py, simple/stats/stat_var_hierarchy_generator.py, simple/tests/stats/stat_var_hierarchy_generator_test.py, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/basic_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/main_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/three_unrelated_svs_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/two_related_svs_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/input/main.mcf
* Added test for [main.in.mcf](https://source.corp.google.com/piper///depot/google3/datacommons/prophet/flume_generator/test_data/svg/main.in.mcf) from G3 and can add tests for more over time.
* Fixed a bug where if there were multiple SVs in the same leaf, it only added one of them. (Testing `main.in.mcf` surfaced this bug.)
* Changed the SVG output to be sorted by SVG ID - makes it easier to follow the hierarchy visually.
* Also, separating camel case words when generating SVG names now to make the names consistent with main DC generated names.
=> Add support for testing SVG hierarchy with MCF inputs.

simple/stats/db.py, simple/tests/stats/test_data/variable_per_row_importer/expected/namespace_prefixes.db.csv, simple/tests/stats/test_data/variable_per_row_importer/input/namespace_prefixes.csv, simple/tests/stats/variable_per_row_importer_test.py
* Ran into this issue when import UN WHO files.
* Namespaces are already removed when inserting into the triples table.
=> Remove namespace prefixes from dcids when inserting into the observations table.

simple/stats/nodes.py, simple/stats/runner.py, simple/stats/schema_constants.py, simple/stats/stat_var_hierarchy_generator.py, simple/tests/stats/nodes_test.py, simple/tests/stats/test_data/events_importer/expected/countryalpha3codes.triples.db.csv, simple/tests/stats/test_data/events_importer/expected/idcolumns.triples.db.csv, simple/tests/stats/test_data/nodes/expected/triples.csv, simple/tests/stats/test_data/runner/expected/config_driven/triples.db.csv, simple/tests/stats/test_data/runner/expected/config_with_wildcards/triples.db.csv, simple/tests/stats/test_data/runner/expected/generate_svg_hierarchy/triples.db.csv, simple/tests/stats/test_data/runner/expected/input_dir_driven/triples.db.csv, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/basic_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/basic_triples.csv, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/main_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/main_triples.csv, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/three_unrelated_svs_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/three_unrelated_svs_triples.csv, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/two_related_svs_svgs.json, simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/two_related_svs_triples.csv
* This PR puts all hierarchy SVGs under a custom DC root so the custom hierarchy is cleanly separated from any main dc hierarchies.
* It also sets us up to do vertical tagging in the next PR.
=> Put SVGs under a hierarchy root.

simple/stats/data.py, simple/stats/runner.py, simple/stats/stat_var_hierarchy_generator.py, simple/tests/stats/runner_test.py, simple/tests/stats/test_data/runner/expected/generate_svg_hierarchy/triples.db.csv, simple/tests/stats/test_data/runner/input/generate_svg_hierarchy/nodes.mcf
* Also updated the generator to return svg specialized names to the runner. This will be used in a follow up PR to generate json equivalent of the [StatVarGroups](https://source.corp.google.com/piper///depot/google3/datacommons/proto/prophet/cache_data.proto;l=338?q=StatVarGroups) cache.
=> Wire schema names into sv hierarchy generator.

build/ci/cloudbuild.push.yaml
The current trigger (using config cloudbuild.java.yaml) runs on branches other than master as well. Since Java checks already run on presubmit, I am removing them from this trigger's config which runs post-submit. When editing the import-push-java trigger, I'll also change it to run only on pushes to master.
=> Remove Java checks from new push trigger config

simple/stats/nodes.py, simple/stats/observations_importer.py, simple/stats/variable_per_row_importer.py, simple/tests/stats/observations_importer_test.py, simple/tests/stats/runner_test.py, simple/tests/stats/test_data/runner/expected/remote_entity_types/key_value_store.db.csv, simple/tests/stats/test_data/runner/expected/remote_entity_types/nl/sentences.csv, simple/tests/stats/test_data/runner/expected/remote_entity_types/observations.db.csv, simple/tests/stats/test_data/runner/expected/remote_entity_types/triples.db.csv, simple/tests/stats/test_data/runner/input/remote_entity_types/config.json, simple/tests/stats/test_data/runner/input/remote_entity_types/remote_entity_types.json, simple/tests/stats/test_data/runner/input/remote_entity_types/variable_per_column.csv, simple/tests/stats/test_data/runner/input/remote_entity_types/variable_per_row.csv, simple/tests/stats/variable_per_row_importer_test.py
* SV summary in CDC currently does not work if the data is provided in variable per row (aka svobs) format.
* This was because we were not populating entities from those files in the sql db.
* With this fix, we fetch entity types for all unique entities from base dc and record them in sql.
* The fix applies this approach to variable per column files as well for consistency.
=> Populate entity with type by calling base DC.

simple/util/dc_client.py
* This change correctly reads dc responses for reference properties like `typeOf`.
=> Look for dcids in dc responses if values are not present.

simple/stats/db.py, simple/tests/stats/db_test.py
* This PR creates DB indexes for better performance as part of loading data itself.
+ Without this, partners would need to create the indexes themselves and we'd have to document it.
* As an optimization, at start of load data, we first drop any existing indexes so that insertions are faster. And we add the indexes only as the final step (after all data has been loaded) before committing the transaction.
=> Create db indexes programmatically.

simple/stats/constants.py, simple/stats/nl.py, simple/stats/runner.py, simple/stats/schema_constants.py, simple/tests/stats/nl_test.py, simple/tests/stats/runner_test.py, simple/tests/stats/test_data/nl/expected/topic_triples/custom_dc_topic_cache.json, simple/tests/stats/test_data/nl/input/topic_triples.csv, simple/tests/stats/test_data/runner/expected/topic_nl_sentences/nl/custom_dc_topic_cache.json, simple/tests/stats/test_data/runner/expected/topic_nl_sentences/triples.db.csv, simple/tests/stats/test_data/runner/input/topic_nl_sentences/schema.mcf
* For an example topic cache json, refer [this one](https://github.com/datacommonsorg/website/blob/204ee2668d6e800f1a554c60066057d638f424ad/server/tests/lib/test_data/topic_cache/input/merge_with_undata/datacommons/nl/custom_dc_topic_cache.json#L4).
* The generated json does not include the `dc` field, so that it is merged with the main dc cache itself. [reference](https://github.com/datacommonsorg/website/blob/204ee2668d6e800f1a554c60066057d638f424ad/server/lib/topic_cache.py#L238)
* Currently the cache is only generated for topics and not for SV peer groups.
+ @dwnoble - let me know if this is needed and I can add it in a follow-up PR.
=> Add support for generating topic cache.

run_test.sh
Running yapf with -vv revealed that it was also attempting to format files in simple/.env.
isort was also erroring so I reformatted its arguments.
=> Fix lint modes of run_test.sh

simple/stats/data.py, simple/stats/logger.py, simple/stats/main.py, simple/stats/observations_importer.py, simple/stats/variable_per_row_importer.py, simple/tests/stats/runner_test.py, simple/tests/stats/test_data/runner/expected/namespace_prefixes/key_value_store.db.csv, simple/tests/stats/test_data/runner/expected/namespace_prefixes/nl/sentences.csv, simple/tests/stats/test_data/runner/expected/namespace_prefixes/observations.db.csv, simple/tests/stats/test_data/runner/expected/namespace_prefixes/triples.db.csv, simple/tests/stats/test_data/runner/input/namespace_prefixes/config.json, simple/tests/stats/test_data/runner/input/namespace_prefixes/observations.csv, simple/tests/stats/test_data/runner/input/namespace_prefixes/remote_entity_types.json, simple/tests/stats/test_data/runner/input/namespace_prefixes/schema.mcf
* Without this fix, the entity types for entities with dcids were not returned by the DC API.
* This resulted in "no data available" messages on the stat var summary pages.
+ See: https://issuetracker.google.com/issues/383559947
* Unrelated, this PR also makes the log level configurable via an env variable which is helpful for debugging.
=> Strip namespaces from entity dcids before fetching their types.

simple/stats/main.py, simple/util/filesystem.py
When running a data import, if the GCS input bucket wasn't created as an empty blob, the import will fail with the error:
```
FileNotFoundError: File not found: gs://YOUR_BUCKET/input
```
* We have a helper method `_fix_gcsfs_storage` that initializes "subdirectories" under the GCS input path as empty blobs, but if the input directory itself was not an empty blob the import fails.
* This PR moves the call to `_fix_gcsfs_storage` to earlier in the execution flow to account for the case where the input directory itself is not an empty blob.
Additional context b/386254730
=> fixed a bug where data imports failed if the GCS input path was not initialized with an empty blob.

simple/stats/db.py, simple/tests/stats/test_data/db/input/sqlite_current_schema_populated.sql, simple/tests/stats/test_data/db/input/sqlite_old_schema_populated.sql, simple/tests/stats/test_data/runner/input/input_dir_driven_with_existing_old_schema_data/sqlite_old_schema_populated.sql, simple/tests/stats/test_data/runner/input/schema_update_only/sqlite_old_schema_populated.sql
- Improves performance from 30s+ to <200ms
- @keyurva it turns out no SQL query changes are necessary. The query we were experimenting with the other day ended up not being exactly right, but it looks like these indices solve the performance issue
- Tested locally against undata-staging instance
Before:
```
2025/02/28 13:41:49 util.go:474: SQL: GetSVSummaries: 34.594636042s
```
After:
```
2025/02/28 13:43:55 util.go:474: SQL: GetSVSummaries: 141.155ms
```
=> Added new db indices to improve performance of getStatVarSummaries query

pipeline/ingestion/src/main/java/org/datacommons/Entity.java, pipeline/ingestion/src/main/java/org/datacommons/IngestionOptions.java, pipeline/ingestion/src/main/java/org/datacommons/Observation.java, pipeline/ingestion/src/main/java/org/datacommons/SpannerClient.java
Making the table names configurable allows loading into tables with different names without requiring code changes.
Example:
```
mvn -Pdataflow-runner compile exec:java -pl ingestion -am -Dexec.mainClass=org.datacommons.IngestionPipeline \
-Dexec.args="... --spannerNodeTableName=Nodex --spannerEdgeTableName=Edgex --spannerObservationTableName=Observationx"
```
Note that the formatting changes were applied by the standard vscode formatter. We should choose a formatter and go with it moving forward.
=> Make spanner table names configurable.

pipeline/ingestion/src/main/java/org/datacommons/CacheReader.java, pipeline/ingestion/src/main/java/org/datacommons/Entity.java, pipeline/ingestion/src/main/java/org/datacommons/SpannerClient.java, pipeline/ingestion/src/test/java/org/datacommons/IngestionTest.java
* Only create self edge when value is /not/ empty 
* Add a new field "nodeId" for creating nodes. This is because the node is always about the EntityInfo, but this sometimes corresponds to subjectId and sometimes the objectId. (This was more of a temporary fix to unblock, but maybe as a follow up we can handle the in/out edges separately, since they differ in a few ways)
* Don't create nodes for terminal edges since there's no object 
* Add type from cache key if not specified in EntityInfo (it looks like it might only be specified for multiple types)
* Add some more unit tests
=> Spanner ingestion fixes

pom.xml, util/src/main/java/org/datacommons/proto/Debug.java, util/src/main/java/org/datacommons/proto/LogLocation.java, util/src/main/java/org/datacommons/proto/Mcf.java, util/src/main/java/org/datacommons/proto/Recon.java, util/src/main/java/org/datacommons/proto/Resolve.java, util/src/main/java/org/datacommons/util/McfChecker.java, util/src/main/proto/resolve.proto, util/src/test/java/org/datacommons/util/StatVarStateTest.java
Already deprecated from mixer: https://github.com/datacommonsorg/mixer/pull/1553
Also updated the version for fmt-maven-plugin since there were compilation errors, which edited the styling on some other files
=> Deprecate ResolveResponse.Entity.resolved_ids from import

pipeline/ingestion/README.md, pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/CacheReader.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/Observation.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/ProtoUtil.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/IngestionPipeline.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/IngestionPipelineOptions.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/SkipProcessing.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/Transforms.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/spanner/SpannerClient.java, pipeline/ingestion/src/test/java/org/datacommons/ingestion/data/CacheReaderTest.java, pipeline/model/src/main/proto/storage.proto
* Combined handling of graph and obs vs forking them earlier.
* Uses group-by for both.
* Experimented and landed on grouping keys that work well for the respective tables.
* Updated the default number of shards to a value that provides a good balance of batch size and distribution.
=> Scale observation imports.

pipeline/ingestion/README.md, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/IngestionPipelineOptions.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/Transforms.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/spanner/SpannerClient.java
Changes
- Use GBK only for graph mutations. Observations can be written directly.
- Limit default sharding to be 1. This helps in co-locating all rows for a subject-id in same bundle -> same spanner batch -> less splits per batch
- Filter duplicate edges before and after GBK
- Update spanner IO config for better throughput
=> [Ingestion pipeline] Ingest observations without GroupByKey

simple/tests/stats/db_test.py, simple/tests/stats/test_data/runner/expected/config_driven/datacommons.sql, simple/tests/stats/test_data/runner/expected/config_with_wildcards/datacommons.sql, simple/tests/stats/test_data/runner/expected/empty_initialized_db/datacommons.sql, simple/tests/stats/test_data/runner/expected/generate_svg_hierarchy/datacommons.sql, simple/tests/stats/test_data/runner/expected/input_dir_driven/datacommons.sql, simple/tests/stats/test_data/runner/expected/input_dir_driven_with_existing_old_schema_data/datacommons.sql, simple/tests/stats/test_data/runner/expected/namespace_prefixes/datacommons.sql, simple/tests/stats/test_data/runner/expected/remote_entity_types/datacommons.sql, simple/tests/stats/test_data/runner/expected/schema_update_only/datacommons.sql, simple/tests/stats/test_data/runner/expected/sv_nl_sentences/datacommons.sql, simple/tests/stats/test_data/runner/expected/topic_nl_sentences/datacommons.sql, simple/tests/stats/test_data/runner/expected/with_subdirs_excluded/datacommons.sql, simple/tests/stats/test_data/runner/expected/with_subdirs_included/datacommons.sql
* I was looking into the [test failures](https://pantheon.corp.google.com/cloud-build/builds/989579a7-8b01-4727-9ac2-6429d0596bda?project=datcom-ci&pli=1&e=13803378&mods=-monitoring_api_staging&invt=Abyoyg&inv=1) in @kmoscoe's PR and found that the goldens didn't include the new indexes that are now created.
* This fix is to incorporate those indexes in our tests.
=> Fix tests by incorporating the new indexes.

simple/stats/config.py, simple/stats/runner.py, simple/tests/stats/nl_test.py, simple/tests/stats/test_data/nl/expected/sv_and_topic_triples/custom_catalog.yaml, simple/tests/stats/test_data/nl/expected/sv_and_topic_triples/custom_dc_topic_cache.json, simple/tests/stats/test_data/nl/expected/sv_and_topic_triples/sentences.csv, simple/tests/stats/test_data/nl/input/sv_and_topic_triples.csv, simple/tests/stats/test_data/runner/expected/sv_nl_sentences/nl/custom_dc_topic_cache.json, simple/tests/stats/test_data/runner/expected/sv_nl_sentences/nl/sentences.csv, simple/tests/stats/test_data/runner/expected/topic_nl_sentences/nl/sentences.csv, simple/tests/stats/test_data/runner/input/topic_nl_sentences/config.json
* Always generates embeddings for both SVs and topics if they are present.
* The topic json will be generated only if topics are present.
* Removes the `generateTopics` config field.
+ Existence of it won't cause issues, it will just be ignored.
+ @kmoscoe - if this field is documented, we should remove it.
+ @dwnoble - UN might be specifying this field in their `config.json`. Like I mentioned, it should not be an issue but best to remove it since it will be ignored hereon.
=> Always generate embeddings for both SVs and topics.

pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/Observation.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/IngestionPipelineOptions.java, pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/Transforms.java, pipeline/ingestion/src/test/java/org/datacommons/ingestion/data/CacheReaderTest.java
* Creates 1 node and 4 edges for each time series.
* Using the type `StatVarObsSeries` for these nodes. We'll need this type to be defined in the schema.
* Currently creates 4 edges for each obs series - name, type, variable measured and observation about.
+ We can add any other edges we need in this PR or later.
*  Currently, the obs series DCID is used for nodes and edges but is not recorded in the Observation table.
+ We can add it later if there's a use case for it.
* This feature is behind a flag (`--writeObsGraph`, `false` by default) until we decide we want to do this or not for sure.
=> Create obs series nodes and edges.

pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/GraphReader.java, pipeline/ingestion/src/test/java/org/datacommons/ingestion/data/GraphReaderTest.java, util/src/main/java/org/datacommons/util/GraphUtils.java
This PR adds some helper routines to convert McfGraph and McfOptimizedGraph to Spanner Graph mutations for populating Node/Edge and Observation tables.
=> Spanner graph ingestion utils

util/src/main/java/org/datacommons/util/PlaceSeriesSummary.java, util/src/test/java/org/datacommons/util/PlaceSeriesSummaryTest.java, util/src/test/resources/org/datacommons/util/Pre1900PlaceSeriesSummaryTest.mcf
The JFreeChart library throws an `IllegalArgumentException` when handling dates before 1900. This was causing the import process to crash (see b/424329091).
This fix adds a check to the `getTimeSeriesSVGChart` method to handle dates before 1900 gracefully. Instead of crashing, the method now returns a user-friendly message. A regression test has been added to ensure this bug does not recur.
=> fix: Handle pre-1900 dates gracefully

pipeline/pom.xml, pipeline/util/pom.xml, pom.xml, server/pom.xml, tool/pom.xml, util/pom.xml
Follow up to https://github.com/datacommonsorg/import/commit/4c2964f0c1961c084d8ec1ca0952ce08dd15cede 
It looks like parent versions need to be explicitly set to compile the ingestion module to run the ingestion pipeline. (Apparently revision is a special property that allows this, but custom properties do not) 
To keep the stable modules (0.1-alpha.1) separate from the development modules (0.1-SNAPSHOT, which is currently set for revision), I have to set the parent versions directly. 
Tested by running ingestion pipeline
=> Fix parent versions in pom.xml

simple/kg_util/mcf_parser.py
This PR introduces a small but important fix to correctly parse CSV-like value lists with leading spaces after commas
`_parse_values` currently uses Python’s `csv.reader` without `skipinitialspace=True`. When values are written as a comma‑separated list of quoted strings with a space after each comma (`, "`), the parser over‑splits on commas that are inside the quoted strings. This change enables `skipinitialspace=True` in `_parse_values` so quoted fields are handled correctly. No other parsing behavior changes.
MCF lines can contain lists with multiple values as CSV‑like, quoted strings, for example:
```mcf
searchDescription: "A, A", "B, B", "C, C, C", "D"
```
With the current implementation:
```python
for values in reader([values_str]):  
...
```
the leading space after each comma means …
=> Fix mcf parser error when dealing with lists of quoted strings

simple/stats/config.md, simple/stats/config.py, simple/stats/nodes.py, simple/stats/runner.py, simple/stats/stat_var_hierarchy_generator.py, simple/tests/stats/config_test.py, simple/tests/stats/nodes_test.py, simple/tests/stats/stat_var_hierarchy_generator_test.py
This PR adds config-driven customisation for a number of settings which are currently hardcoded (ID namespace, SVG prefix, root statvar group name, hierarchy properties blocklist).  
It's the first in a small series of PRs which will focus on improving how statvar and groups Ids are generated to improve the front-end experience and make IDs deterministic.
Given hardcoded constants in the code, with no overrides possible:
- Generated IDs for SVs and manual groups were fixed to a default namespace .
- The StatVarGroup hierarchy always used a fixed custom prefix and root name .
- No way to extend the SV property blocklist used during hierarchy generation. This means potentially messy hierarchies if additional properties are used for StatVar nodes.
- Config
- `customIdNamespace`: controls …
=> Support custom ID namespace, SVG prefix, root SVG name
