datacommonsorg/import

- README.md
- util/src/main/java/org/datacommons/util/McfParser.java
- util/src/main/java/org/datacommons/util/Vocabulary.java
- util/src/test/java/org/datacommons/util/McfParserTest.java
This PR includes no logic change.
> Reformat code using google-java-format

- README.md
- build.sh
- cloudbuild.java.yaml
- pom.xml
- test.sh
- util/src/main/java/org/datacommons/proto/Mcf.java
- util/src/main/java/org/datacommons/util/McfParser.java
- util/src/test/java/org/datacommons/util/McfParserTest.java
Rely on maven to generate protoc and format code by using different plugins.  Also upgrade Java from 8 to 11.
> Add protoc generation and formatting to pre-submit

- tool/src/main/java/org/datacommons/tool/Processor.java
- util/src/main/java/org/datacommons/util/LogWrapper.java
- util/src/main/java/org/datacommons/util/TestUtil.java
- util/src/main/java/org/datacommons/util/TmcfCsvParser.java
- util/src/test/java/org/datacommons/util/TmcfCsvParserTest.java
- added counters for NumRowSuccesses, NumPVSuccesses, NumNodeSuccesses
- should persistLog even if there are no warnings or errors to show the new counters
> Add general stat counters

- util/src/main/java/org/datacommons/util/ComplexValueParser.java
- util/src/main/java/org/datacommons/util/McfChecker.java
- util/src/main/java/org/datacommons/util/McfMutator.java
- util/src/main/java/org/datacommons/util/McfParser.java
- util/src/main/java/org/datacommons/util/TmcfCsvParser.java
- util/src/test/java/org/datacommons/util/ComplexValueParserTest.java
- util/src/test/java/org/datacommons/util/McfCheckerTest.java
- util/src/test/java/org/datacommons/util/TmcfCsvParserTest.java
This was programmed together with Jennifer and Carolyn.
> Improve user messages by following a consistent format

- util/src/main/java/org/datacommons/util/ComplexValueParser.java
- util/src/main/java/org/datacommons/util/LogCb.java
- util/src/main/java/org/datacommons/util/McfChecker.java
- util/src/main/java/org/datacommons/util/McfParser.java
- util/src/main/java/org/datacommons/util/McfUtil.java
- util/src/main/java/org/datacommons/util/StringUtil.java
- util/src/main/java/org/datacommons/util/TmcfCsvParser.java
- util/src/test/java/org/datacommons/util/LogCbTest.java
- util/src/test/java/org/datacommons/util/McfParserTest.java
- util/src/test/java/org/datacommons/util/McfUtilTest.java
- util/src/test/java/org/datacommons/util/StringUtilTest.java
This is a pure refactor with 0 logic change
> Refactor functions into StringUtil, LogCb

- tool/src/main/java/org/datacommons/tool/Args.java
- tool/src/main/java/org/datacommons/tool/GenMcf.java
- tool/src/main/java/org/datacommons/tool/Lint.java
- tool/src/main/java/org/datacommons/tool/Main.java
- tool/src/main/java/org/datacommons/tool/Processor.java
- tool/src/main/java/org/datacommons/tool/WriterPair.java
- tool/src/test/java/org/datacommons/tool/TestUtil.java
- tool/src/test/resources/org/datacommons/tool/genmcf/fataltmcf/output/report.json
- tool/src/test/resources/org/datacommons/tool/genmcf/resolution/output/report.json
- tool/src/test/resources/org/datacommons/tool/genmcf/statchecks/output/report.json
- tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/output/report.json
- tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/report.json
- tool/src/test/resources/org/datacommons/tool/lint/mcfonly/output/report.json
- tool/src/test/resources/org/datacommons/tool/lint/nocsv/output/report.json
- tool/src/test/resources/org/datacommons/tool/lint/statchecks/output/report.json
- util/src/main/java/org/datacommons/proto/Debug.java
- util/src/main/proto/Debug.proto
Also, refactor a couple of classes out of Processor into its own file.
> Store command-line options in report.json and print on command line

- tool/src/test/resources/org/datacommons/tool/genmcf/successtmcf/output/summary_report.html
- tool/src/test/resources/org/datacommons/tool/lint/allfiletypes/output/summary_report.html
- util/src/main/java/org/datacommons/util/McfChecker.java
- util/src/main/java/org/datacommons/util/PlaceSeriesSummary.java
- util/src/main/java/org/datacommons/util/StatChecker.java
- util/src/main/java/org/datacommons/util/Vocabulary.java
- util/src/test/java/org/datacommons/util/McfCheckerTest.java
1. Summary report had incorrect unit, scaling-factor
2. Add lgdCode, udiseCode for resolution
3. Strip dcAggregate/ prefix before existence checks
> Fix some minor bugs

- README.md
- tool/src/main/java/org/datacommons/tool/Main.java
- add an instruction in the README for getting information about flags that can be set
- update what the default value is for some flags
> update documentation about flags

- build/cloudbuild.npm.yaml
- wizard/.eslintignore
- wizard/README.md
- wizard/package.json
- wizard/src/index.ts
- wizard/src/types.ts
- wizard/src/utils/detect_place.test.tsx
- wizard/src/utils/detect_place.ts
- wizard/src/utils/file_generation.ts
- wizard/src/utils/heuristics.ts
- wizard/webpack.config.js
- add linting and fix current lint errors
- update CsvData type
> [beast] lint and type updates

- wizard/src/components/page.tsx
- wizard/src/components/upload_section.tsx
- wizard/src/index.html
- wizard/src/style.css
- wizard/src/types.ts
- wizard/webpack.config.js
> [beast] add upload file section

- wizard/src/components/mapping_column_options.tsx
- wizard/src/components/mapping_section.tsx
- wizard/src/components/mapping_table.tsx
- wizard/src/components/mapping_table_header.tsx
- wizard/src/components/preview_section.tsx
- wizard/src/index.html
- wizard/src/style.scss
- wizard/src/types.ts
- wizard/src/utils/file_generation.test.ts
- wizard/src/utils/file_generation.ts
- wizard/src/utils/obs_generation.test.tsx
- wizard/src/utils/tmcf_generation.test.tsx
- wizard/src/utils/tmcf_generation.ts
- wizard/src/utils/validation.test.tsx
- wizard/src/utils/validation.ts
- wizard/webpack.config.js
- fix column highlighting problem
- update naming of mapped things
- update styling for buttons, radio inputs, and table headers
- add favicon
updated at: https://chejennifer.github.io/import/wizard
> [Beast] Various small fixes

- wizard/src/index.html
- update info section to include States
https://chejennifer.github.io/import/wizard/ updated
> [beast] Update info section

- util/src/main/java/org/datacommons/util/Vocabulary.java
- wizard/src/utils/tmcf_generation.test.tsx
- wizard/src/utils/tmcf_generation.ts
Followup mixer change in https://github.com/datacommonsorg/mixer/pull/872, g3 change in cl/460723945
> Fix bug in Wizard; add fips52AlphaCode for resolution

- util/src/main/java/org/datacommons/util/Vocabulary.java
Fix related to issue: https://github.com/datacommonsorg/import/issues/181
> Add countryAlpha3Code and countryNumericCode as resolvable place IDs

- util/src/main/java/org/datacommons/util/NameResolver.java
- util/src/test/java/org/datacommons/util/NameResolverTest.java
* Will be integrated with the tool in the next PR.
> Add resolver to resolve nodes with names.

- simple/stats/constants.py
- simple/stats/importer.py
- simple/stats/main.py
- simple/stats/reporter.py
- simple/stats/runner.py
- simple/stats/sample/output/process/report.json
* Reports status on overall and individual file imports.
* Support for reporting more details will be added in subsequent PRs.
> Generate an initial report.json when running the importer.

- simple/README.md
- simple/stats/config.md
- simple/stats/importer.py
- simple/stats/main.py
- simple/stats/reporter.py
- simple/util/ngram_matcher.py
* This allows website to capture the stdout properly.
* Fixed some markdown formatting.
> Redirect RSI script logging to stdout

- build/cloudbuild.py.yaml
- run_test.sh
- simple/requirements.txt
- simple/sample/input/config.json
- simple/sample/output/process/debug_resolve_powerplants.csv
- simple/sample/output/process/report.json
- simple/sample/output/triples.csv
- simple/stats/config.md
- simple/stats/config.py
- simple/stats/data.py
- simple/stats/runner.py
- simple/stats/triples.py
- simple/tests/__init__.py
- simple/tests/stats/__init__.py
- simple/tests/stats/config_test.py
- simple/tests/stats/data_test.py
* Added support for SV hierarchy (groups), description, name overrides and NL sentences.
+ Updated config doc describing these.
* Added initial unit tests.
* Added options to `run_test.sh`.
> Add support for SV hierarchy.

- build/ci/cloudbuild.push_simple.yaml
* Verified by triggering the gcloud build manually.
* Will create the PR trigger after this one is in.
> Create cloudbuild to be triggered on each PR.

- simple/util/dc_client.py
* This method will be used to fetch schema names to generate specialized SVG names.
> Add method to fetch a given property from multiple entities.

- simple/stats/db.py
- simple/tests/stats/db_test.py
- simple/tests/stats/test_data/db/expected/schema.mcf
* This will be used to generate SVG cache.
> Add functionality to fetch entity names from sql.

- simple/requirements.txt
- simple/stats/stat_var_hierarchy_generator.py
- simple/tests/stats/stat_var_hierarchy_generator_test.py
- simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/basic_svgs.json
- simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/main_svgs.json
- simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/svs_with_mprops_svgs.json
- simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/three_unrelated_svs_svgs.json
- simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/two_related_svs_svgs.json
- simple/tests/stats/test_data/stat_var_hierarchy_generator/expected/verticals_svgs.json
* Mapping to schema names will be in a follow up PR.
> Generate special svg names.

- simple/stats/db.py
- simple/stats/schema.py
- simple/tests/stats/schema_test.py
* The names will be used for generating svg hierarchy group names.
> Add method to get names from both sql and remote dc.

- simple/stats/db.py
* To support versioning, we'll be creating databases on cloud sql instances programmatically.
* This PR adds support for this in preparation of the larger versioning effort.
* The implementation is backward compatible since it creates a db only if one does not already exist.
* Tested locally by running the db script which created [this db](https://screenshot.googleplex.com/AKLsZXqUXVRBob3) programmatically.
> Create Cloud SQL db programmatically if it does not exist.

- simple/stats/data.py
- simple/stats/variable_per_row_importer.py
- simple/tests/stats/test_data/variable_per_row_importer/expected/row_obs_props/observations.db.csv
- simple/tests/stats/test_data/variable_per_row_importer/input/row_obs_props/config.json
- simple/tests/stats/test_data/variable_per_row_importer/input/row_obs_props/input.csv
- simple/tests/stats/variable_per_row_importer_test.py
* Note that this is only supported for the `variablePerRow` format at this time.
> Add support for specifying obs properties per row.

- run_test.sh
- simple/requirements.txt
- simple/tests/util/file_match_test.py
- simple/tests/util/filesystem_test.py
- simple/util/file_match.py
- simple/util/filesystem.py
This lays the foundation for [supporting multiple input dirs](https://github.com/datacommonsorg/import/pull/352).
> Add utils for PyFilesystem and config key matching

- simple/stats/events_importer.py
- simple/stats/logger.py
- simple/stats/main.py
- simple/stats/nl.py
- simple/stats/nodes.py
- simple/stats/runner.py
- simple/stats/variable_per_row_importer.py
- Updated log formatting to be more readable in custom DC
- Removed duplicate log messages
Before:
```
Index created: observations_entity_variable
I1202 18:24:17.969703 140586157779840 db.py:546] Index created: observations_entity_variable
Creating index: triples_subject_id
I1202 18:24:17.969856 140586157779840 db.py:544] Creating index: triples_subject_id
Index created: triples_subject_id
I1202 18:24:17.995120 140586157779840 db.py:546] Index created: triples_subject_id
```
https://screenshot.googleplex.com/8aYB3N5uJok7R77
After:
```
[2024-12-19 22:42:23,647 INFO db.py:435] Index created: observations_entity_variable
[2024-12-19 22:42:23,647 INFO db.py:433] Creating index: triples_subject_id
[2024-12-19 22:42:23,647 INFO db.py:435] Index created: triples_subject_id
```
> Updated stats importer logging

- simple/README.md
This aligns with Mixer as of https://github.com/datacommonsorg/mixer/pull/1491.
> Change recommended protoc version to 3.21.12.

- pipeline/ingestion/src/main/java/org/datacommons/SpannerClient.java
- pipeline/ingestion/src/test/java/org/datacommons/IngestionTest.java
* Example run with this change: http://shortn/_des1ea6wGb
> Apply distinct transform on node mutations.

- pipeline/ingestion/README.md
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/IngestionPipelineOptions.java
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/Transforms.java
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/spanner/SpannerClient.java
- Address review comment from pr https://github.com/datacommonsorg/import/pull/380
- Added documentation for selecting working configuration.
- Updated de-duplication logic to key level (within values of a key) from bundle level
> Address review comment from pr 380

- pipeline/ingestion/pom.xml
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/CacheReader.java
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/GraphReader.java
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/data/Node.java
- pipeline/ingestion/src/main/java/org/datacommons/ingestion/pipeline/Transforms.java
- pipeline/ingestion/src/test/java/org/datacommons/ingestion/data/CacheReaderTest.java
- pipeline/ingestion/src/test/java/org/datacommons/ingestion/data/GraphReaderTest.java
* Only set type Thing for reference nodes
* Update node equality so tests catch this
> Fix default type for ingestion
